# EM Plex Updater Configuration
# Change the settings below to reflect your PMS instance
# Rename & place this file in ~/.config/plex-updater/config.yml

# Your Plex Media Server's unique client ID
# 1 - Log in to app.plex.tv/web/app
# 2 - Navigate to Settings -> Server
# 3 - Look at the browser's URL, it will look something like this:
#     https://app.plex.tv/web/app#!/settings/server/ZdvOD8932rsJQzytoF1hZB1gvLXm2o8VUpaiE3Wx/general
#     The long set of numbers and letters after "server" is your client ID
client: ZdvOD8932rsJQzytoF1hZB1gvLXm2o8VUpaiE3Wx

# Your Plex.tv account's user name and password
#    If you encounter any errors related to these fields,
#    try wrapping them in quotes, e.g. "joe_smith"
username: joe_smith
password: OhNJ45BzDUhPqZ

# Use Plex Pass downloads feed instead of the public one.
#   Your user account must have an active Plex Pass subscription
#   in order to use this feature.
# Options: on, off
plex_pass: off

# Specify which system you are using Plex on
# Available options: Computer, NAS
system_type: Computer

# Specify which operating system you are using
# Computer options: Windows, Mac, Linux, FreeBSD
# NAS options: Synology, Netgear, QNAP, unRAID, Drobo, ASUSTOR, Thecus, Seagate, Western Digital
system_os: Linux

# (Optional) Specify which build of OS you would like to download
# This is required for Linux and most NAS systems
# Linux options: Ubuntu 64-bit, Ubuntu 32-bit, Fedora 64-bit, Fedora 32-bit, CentOS 64-bit, CentOS 32-bit
# Synology: Intel, ARMv7
# Netgear: Intel 6.x, ARM 6.x, ARM 6.x RN2xx
# QNAP: Intel, ARMv7
# ASUSTOR: Intel 64-bit, Intel 32-bit, ARMv7
# Thecus: Intel 64-bit, Intel 32-bit
# Seagate: Intel, ARMv7
# Western Digital: Mirror, Mirror Gen2, EX2, EX2100, EX4100, DL2100, DL4100
system_build: Ubuntu 32-bit

# Specify where EM Plex Updater should save downloaded package files
folder: /home/username/downloads

# Specify if EM Plex Update should remove the downloaded package file
#    after it has succesfully completed installing it.
# Options: on, off
remove_completed: off
